name: CI/CD Pipeline

on:
  push:
    branches: [ Wail ]
  pull_request:
    branches: [ Wail ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        
    - name: Install Composer
      run: composer install --no-interaction --prefer-dist --no-progress
        
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse
        
    - name: Run PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff
        
    - name: Run PHP Security Checker
      run: composer require sensiolabs/security-checker && vendor/bin/security-checker security:check composer.lock
        
    - name: Run PHP Mess Detector
      run: vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: notes_esigelec
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        
    - name: Install Composer
      run: composer install --no-interaction --prefer-dist --no-progress
        
    - name: Run PHPUnit
      run: vendor/bin/phpunit
      env:
        DB_HOST: 127.0.0.1
        DB_NAME: notes_esigelec
        DB_USER: root
        DB_PASS: ''

  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif

  deploy:
    needs: [security, test, codacy-analysis]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Wail'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
       