name: CI/CD Pipeline

on:
  push:
    branches: [ Wail ]
  pull_request:
    branches: [ Wail ]

jobs:
  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif

  deploy:
    needs: [codacy-analysis]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Wail'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
       